### ISSUE TITLE
[optimize] many storage load

### ISSUE THREAD

**Issue by DevUreak** [tokamak-network/crossTrade#27]
**Describe the bug**
Your code has a many storage load. If you declare it in memory and refer to it, you can save a lot of gas costs. 
If other .sol files also contain this part, it would be possible to reduce gas costs for users when using the service.

**Configuration**
- Severity: medium

**Impact**

**Recommendation**
```solidity
//  L2CrossTrade.sol 
  function claimCT(
        address _from,
        uint256 _amount,
        uint256 _saleCount,
        uint256 _chainId,
        bytes32 _hash,
        bool _edit
    )
        external
        payable
        nonReentrant
        checkL1(_chainId)
        providerCheck(_saleCount)
    {
        require(dealData[_saleCount].hashValue == _hash, "Hash values do not match");
        require(dealData[_saleCount].provider == address(0), "already sold");
        if (_edit == false) {
            **require(dealData[_saleCount].fwAmount** == _amount, "not match the fwAmount");
        }

        dealData[_saleCount].provider = _from;
        address l2token = dealData[_saleCount].l2token;
        uint256 totalAmount = dealData[_saleCount].totalAmount;

        if(l2token == legacyERC20ETH) {
            (bool sent, ) = payable(_from).call{value: totalAmount}("");
            require(sent, "claim fail");
        } else {
            IERC20(l2token).safeTransfer(_from,totalAmount);
        }

        emit ProviderClaimCT(
            dealData[_saleCount].l1token,
            l2token,
            dealData[_saleCount].requester,
            _from,
            totalAmount,
            _amount,
            _saleCount
        );
    }
``` 
You can use it like below.

```
RequestData memory _dealData = dealData[_saleCount]; 
```

**Exploit Scenario **

**Demo**

**Comment by suahnkim** [comment]
@DevUreak 
I think solidity compiler optimization assigns memory (on assembly level) based on the scope of the variable automatically, so that you don't have to declare memory every time. 

If the **optimization is not good** or **if there is a good reason to explicitly communicate that the variable is a memory from code readability perspective** -> then I think you should use it. 

In this case, I am not sure if "memory" is a good use case because, there is a storage modification of the reference variable 
`        dealData[_saleCount].provider = _from;
`
so, declaring a memory does not seem to provide any real benefit from code readability perspective. 

If you can provide gas comparison of the current code and your proposal, I think it maybe helpful for us to understand. **It is possible that the optimization may have to be run many time to achieve enough, in that case, declaring as memory may make more sense**

**Comment by suahnkim** [comment]
since this is related to gas optimization, severity is changed to LOW from Medium @DevUreak
