### ISSUE TITLE
Different `l1Token` and `l2Token` pair order will mostly remain unfulfilled

### ISSUE THREAD

**Issue by parth-15** [tokamak-network/crossTrade#46]
**Describe the bug**
The requesters request the tokens using function `requestRegisteredToken` and `requestNonRegisteredToken`. 

The function `requestNonRegisteredToken` has following check:
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L2/L2CrossTrade.sol#L166

As discussed in issue(https://github.com/tokamak-network/crossTrade/issues/41), the same condition will also needs to be added in function `requestRegisteredToken`. 

However, this condition can be quite problametic for pairs which are not the same and have different price(for ex: ETH/TON or TON/USDT). According to the above condition, if the user requests `5 TON` on `L1` but the `L2 token` is ETH. In that case, `_fwAmount` will be `5` and `_totalAmount` should be more than `5`. So, to get `5 TON`, user would need to spend more than `5 ETH`.

Due to this, pairs with different prices won't be possible to use for this contract.

**Comment by zzooppii** [comment]
I interpret this as the intention of the person registering, so there is no problem with incorrect input in requestNonRegisteredToken.

Our front screen will only support requestRegisteredToken.

This is not a problem because it is not an attack on a vulnerability in the contract, but rather a transaction intended by the requester.

**Comment by usgeeus** [comment]
If the different l1Token and l2Token pair order remain unfulfilled, 
yes the requester can edit, but also can cancel it. 
So even if it remains, it's the requestor's fault, and the funds can be recovered via cancel, so I don't think it's a criticial issue.

**Comment by usgeeus** [comment]
Yes I understand what you mean, thank you.

I believe our business model is based on the assumption that l1token and l2token are the same token for crossTrade, which is why we added that require statement. The require is a safety check for users trading the same token, not for users cross-trading different tokens.

But on second thought after reading your comments, there might be some demand to cross trade different tokens, so it might be better to just remove the require statement.

**Comment by zzooppii** [comment]
@suahnkim How should we view this case?

**Comment by suahnkim** [comment]
Our use case do not support different token pairs for security reasons right now (there are many risks, that I won't go over here).  

But in the future, we will look into supporting different token pairs; however it will probably be composed with a swap dapp to reduce security risks. 

I think we can close the issue.

**Comment by suahnkim** [comment]
1. We won't support any requests/provides made using requestNonRegisteredToken **on our frontend**. This function is there in case someone else wants to support a more sophisticated backend; our core contract assumes that mapping is for the same token. We cannot remove this part as it would severely limit the customization of our service and it can be a legal issue if we do not allow it; because token mapping is an owner function -> not everyone can use this the register their token.   
2. We will eventually support different token pairs, but we first need to support other functions (such as L2 -> L1 -> L2 cross trade). Once we have sorted out other issues then, we will support different token pairs. 
3. When you allow for different token pairs, there are issues with which tokens are genuine, since you can have multiple representation of L1 token on L2. We do not have enough time to figure out sufficient basic checks to resolve this issue right now for different token pairs. Even for the same token pair, I don't think we should open it (and we won't open it on our frontend), but we are opening it on the contract side due to possible legal requirements. Once we have sufficient research, we will add the functionality. But from my research, it is better to use swap to ensure that the **requester always gets the best price**; so the contract will require an overhaul and will have additional checks to support this use case -> which we do not have time to develop.

**Comment by suahnkim** [comment]
Generally speaking, it is harder to design services for different pairs of tokens from the contract side. It is better to stick with the core functionality first and use composability to achieve more competitive results.

**Comment by usgeeus** [comment]
Then I think it would be better to keep the `require` statement in `requestRegisteredToken` function and remove it in `requestNonRegisteredToken` function.

**Comment by usgeeus** [comment]
It looks like we have a few options

1. Remove all that `require` statements from all functions (requestNonRegisteredToken, requestRegisteredToken, edit(l1))

2. Remove the `require` statement in the `requestNonRegisteredToken` function and keep the `require` statement in the `requestRegisteredToken` function. Then The`edit` function of the L1CrossTrade contract should handle different token pairs and same token pairs separately. This creates the inconvenience of having to manage the mapping in L1 as well.

3. By adding a require statement to all 3 functions, we make the requestNonRegisteredToken function effectively unusable.

**Comment by usgeeus** [comment]
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L1/L1CrossTrade.sol#L333
Requestor can modify fwAmount in that function, which makes that `require` statement in L2 request function useless, so we need to consider the edit function in L1 as well.

**Comment by usgeeus** [comment]
Yes, then we should pick either 1 or 2. 
https://github.com/tokamak-network/crossTrade/issues/46#issuecomment-2191209399
What do you think?

**Comment by usgeeus** [comment]
Yes we have to keep the `requestNonRegisteredToken` function anyway for legal reasons.
The `require` statement in `requestNonRegisteredToken` is the problem now, so I think it makes sense to remove it from that function. 

Do you have any thoughts on these 3 options from this [comment](https://github.com/tokamak-network/crossTrade/issues/46#issuecomment-2191209399)? @zzooppii @suahnkim 

I think 1 and 2 should be considered, since I think it doesn't make sense to keep that `require` statement in `requestNonRegisteredToken` function.
If we also going to consider the case of the same token having a different decimal on different chains, then number 1 might be the best choice.

**Comment by suahnkim** [comment]
There was some miscommunication about the problematic requirement statement. 
I wasn't aware why that requirement existed, but it has been explained that it was not supposed to be included in the first place. (I thought it had to be included for a good reason)

So, we will remove the requirement as @parth-15 correctly identified. 
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L2/L2CrossTrade.sol#L166

And we will add some warning on the interface to make sure that users know that the function is not safe. 

the severity is set low, as the issue do not involve any loss in funds, and it is a simple bug that prevents users from using the function to its full extent.

**Comment by suahnkim** [comment]
@zzooppii will remove any related requirements from the code

**Comment by zzooppii** [comment]
I previously entered the Require statement incorrectly.
sorry.
It has been modified. thank you

**Comment by suahnkim** [comment]
> I feel that `1` is good choice. Apart from that as @suahnkim  mentioned, I don't think there is any security vulnerability if we support different token pairs. I think `Cross Trade` platform will be open market and `providers` will only provide the tokens which they find profitable/valuable. The only challenge I see is for frontend to weed out scammy token pairs and only show relevant token pairs. But in my opinion, we shouldn't restrict the functionality only because it is difficult to implement in frontend.

Security issue rises if tokens are not correctly displayed on the front end due to server issues. I don't want to put all the responsibility to the frontend team, if someone gets scammed in getting a false token on L2, we will have to take responsibility for it. Which is why frontend will not support that function. 

Secondly, different pair implemented this way is not good for requester's point of view. Better to create composable contract that is more competitive and safe.

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/a6fbc389a6452e4932037c8881be14423351a424

require has been removed from this commit.
I would appreciate it if you could check and close it!
